M48
; DRILL file {KiCad 9.0.7} date 2026-02-15T17:11:46+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-15T17:11:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X40.11Y-72.9
X45.89Y-72.9
T2
X25.5Y-75.0
X25.5Y-77.5
X30.5Y-70.0
X35.5Y-75.0
X35.5Y-77.5
M30
